#!/usr/bin/env node
/* -------------------------------------------------
   Nex – One‑Command Project Bootstrap
   ------------------------------------------------- */

const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');
const inquirer = require('inquirer');

async function bootstrap() {
    const cwd = process.cwd();
    const defaultName = path.basename(cwd);

    // Prompt minimal config
    const answers = await inquirer.prompt([
        { type: 'input', name: 'projectName', message: 'Project name:', default: defaultName },
        { type: 'input', name: 'port', message: 'Port number:', default: '3000' }]);

    // 1️⃣ npm init -y
    console.log('\nInitializing npm project...');
    execSync('npm init -y', { stdio: 'inherit' });
    
    // Update package.json 'main' and add a 'start' script
    const entryFile = `${answers.projectName}.js`;
    let pkgJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));
    pkgJson.main = entryFile;
    pkgJson.scripts = pkgJson.scripts || {};
    pkgJson.scripts.start = `node ${entryFile}`;
    fs.writeFileSync('package.json', JSON.stringify(pkgJson, null, 2));

    // 2️⃣ Prompt for environment name and DB details, then write index.conf manually
    const { env } = await inquirer.prompt([
        { type: 'input', name: 'env', message: 'Environment name (default: Local):', default: 'Local' }
    ]);
    const dbAnswers = await inquirer.prompt([
        { type: 'checkbox', name: 'dbTypes', message: 'Select DB types (optional)', choices: ['mysql', 'mongodb', 'mssql'] },
        { type: 'input', name: 'host', message: 'Database host (default: localhost):', default: 'localhost' },
        { type: 'input', name: 'port', message: 'Database port (default depends on DB):', default: '' },
        { type: 'input', name: 'user', message: 'Database user:', default: '' },
        { type: 'password', name: 'password', message: 'Database password:', mask: '*' },
        { type: 'input', name: 'database', message: 'Database name:', default: '' }
    ]);
    // Build config object
    confObj[env] = {
        APPLICATION_PORT_NUMBER: Number(answers.port),
        DB_TYPE: dbAnswers.dbTypes && dbAnswers.dbTypes.length > 0 ? dbAnswers.dbTypes : ['mongodb'], // Default to mongo if skip
        JWT_TOKEN: answers.jwt ? 'yes' : 'no'
    };
    
    // Explicitly add DB blocks for all supported types if data was provided
    if (dbAnswers.host) {
        const dbConfig = {
            HOST: dbAnswers.host,
            PORT: dbAnswers.port,
            USER: dbAnswers.user,
            PASSWORD: dbAnswers.password,
            DATABASE: dbAnswers.database
        };
        
        // Populate specific blocks based on type selection or all if provided
        if (dbAnswers.dbTypes.includes('mysql')) confObj[env].MYSQL = { ...dbConfig, PORT: dbConfig.PORT || 3306 };
        if (dbAnswers.dbTypes.includes('mongodb') || dbAnswers.dbTypes.length === 0) confObj[env].MONGODB = { ...dbConfig, PORT: dbConfig.PORT || 27017 };
        if (dbAnswers.dbTypes.includes('mssql')) confObj[env].MSSQL = { ...dbConfig, PORT: dbConfig.PORT || 1433 };
    }
    // Save the configuration file exclusively as the project name
    const confFile = `${answers.projectName}.conf`;

    fs.writeFileSync(confFile, JSON.stringify(confObj, null, 2));
    console.log(`✔ ${confFile} created with detailed DB config`);

    // 3️⃣ Scaffold src files
    const indexJs = `
// Auto‑generated by Nex CLI
const { Implementation_Manager, use } = require('sv-nex');
const pingModule = require('./routes/ping');

(async () => {
    try {
        await Implementation_Manager.initializeImplementation();
        Implementation_Manager.initializeHttpAndStartServer({ ping: pingModule });
    } catch (e) {
        console.error('Startup error:', e);
        process.exit(1);
    }
})();
`;
    fs.writeFileSync(entryFile, indexJs.trimStart());
    console.log(`✔ ${entryFile} created`);

    // ---- routes/ping.js ----
    if (!fs.existsSync('routes')) fs.mkdirSync('routes');
    const pingJs = `
const express = require('express');
const router = express.Router();
router.get('/ping', (req, res) => res.json({ status: 'ok' }));
module.exports = { router };
`;
    fs.writeFileSync(path.join('routes', 'ping.js'), pingJs.trimStart());
    console.log(`✔ routes/ping.js created`);

    // 4️⃣ Install runtime deps (express is required for the test route)
    console.log('\nInstalling runtime dependencies...');
    execSync('npm install express', { stdio: 'inherit' });

    // 5️⃣ Start the server automatically
    console.log('\nStarting the server...');
    const server = spawn('node', [entryFile], { stdio: 'inherit' });
    server.on('close', code => {
        console.log(`\nServer exited with code ${code}`);
    });
}

// -------------------------------------------------
const args = process.argv.slice(2);
if (args.length === 0) {
    // Direct execution – bootstrap automatically
    bootstrap();
} else {
    console.log('Unknown arguments. Running bootstrap by default.');
    bootstrap();
}
