#!/usr/bin/env node
/* -------------------------------------------------
   Nex – One‑Command Project Bootstrap
   ------------------------------------------------- */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const inquirer = require('inquirer');
const { NE_Utils } = require('./essentials/utils');

async function bootstrap() {
    const cwd = process.cwd();
    const defaultName = path.basename(cwd);

    console.log('\n\x1b[36m========== NEX PROJECT BOOTSTRAP ==========\x1b[0m\n');

    // 1️⃣ Prompt minimal config (Project name)
    const answers = await inquirer.prompt([
        { type: 'input', name: 'projectName', message: 'Project name:', default: defaultName }
    ]);

    // 2️⃣ npm init -y
    console.log('\n\x1b[32m✔ Initializing npm project...\x1b[0m');
    execSync('npm init -y', { stdio: 'ignore' });

    // 3️⃣ Update package.json 'main' and add necessary scripts
    const entryFile = `${answers.projectName}.js`;
    let pkgJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));
    pkgJson.main = entryFile;
    pkgJson.scripts = pkgJson.scripts || {};
    pkgJson.scripts.start = `node ${entryFile}`;
    pkgJson.scripts.dev = `nodemon ${entryFile}`;
    pkgJson.scripts.setup = `sv-nex setup`;
    pkgJson.scripts.configure = `sv-nex configure Local`;
    pkgJson.scripts.projectstructure = `sv-nex projectstructure`;
    fs.writeFileSync('package.json', JSON.stringify(pkgJson, null, 2));

    // 4️⃣ Scaffold basic framework structure
    const indexJs = `// Auto‑generated by Nex CLI
const { Implementation_Manager, use } = require('sv-nex');
const pingModule = require('./routes/ping');

(async () => {
    try {
        await Implementation_Manager.initializeImplementation();
        Implementation_Manager.initializeHttpAndStartServer({ ping: pingModule });
    } catch (e) {
        console.error('Startup error:', e);
        process.exit(1);
    }
})();
`;
    fs.writeFileSync(entryFile, indexJs.trimStart());
    console.log(`\x1b[32m✔ ${entryFile} created\x1b[0m`);

    // Scaffold routes/ping.js
    if (!fs.existsSync('routes')) fs.mkdirSync('routes');
    const pingJs = `
const express = require('express');
const router = express.Router();
router.get('/ping', (req, res) => res.json({ status: 'ok' }));
module.exports = { router };
`;
    fs.writeFileSync(path.join('routes', 'ping.js'), pingJs.trimStart());
    console.log(`\x1b[32m✔ routes/ping.js created\x1b[0m`);

    // 5️⃣ Install runtime deps (express, sv-nex, nodemon)
    console.log('\n\x1b[32m✔ Installing dependencies (express, nodemon). Please wait...\x1b[0m');
    execSync('npm install express', { stdio: 'inherit' });
    execSync('npm install --save-dev nodemon', { stdio: 'inherit' });

    // 6️⃣ Execute the modernized native setup wizard
    // We mock require.main so NE_Utils detects the correct config name
    require.main = { filename: path.join(cwd, entryFile) }; 
    const { goConfig } = await inquirer.prompt([{ type: 'confirm', name: 'goConfig', message: 'Configure database & environment now?', default: true }]);
    if (goConfig) await NE_Utils.configureEnvironment('Local');
    
    console.log('\n\x1b[32m✔ Project scaffolded beautifully!\x1b[0m');
    const { startServer } = await inquirer.prompt([{ type: 'confirm', name: 'startServer', message: 'Would you like to start the development server now?', default: true }]);
    if (startServer) {
        const { execSync } = require('child_process');
        console.log('\x1b[36m🚀 Starting Nex Server...\x1b[0m\n');
        execSync('npm run dev', { stdio: 'inherit' });
    }
}

// -------------------------------------------------
const args = process.argv.slice(2);

(async () => {
    if (args.length === 0) {
        // Direct execution without args -> Show Main Menu
        await NE_Utils.processCli();
    } else if (args.includes('--bootstrap') || args.includes('bootstrap')) {
        // Forced bootstrap flow
        await bootstrap();
    } else {
        // Pass known args or menu to NE_Utils
        await NE_Utils.processCli();
    }
})().catch(err => {
    console.error("\x1b[31m[ERROR]\x1b[0m", err.message);
    process.exit(1);
});
